### ISSUE TITLE
Extension for Firefox nightly android

### ISSUE THREAD

**Issue by blader-render** [nopecha-ai/nopecha-extension#1]
How to use Extension for Firefox nightly android, because, I already install that extension, but not working.

**Comment by blader-render** [comment]
![az_recorder_20221214_162058](https://user-images.githubusercontent.com/120096290/207556863-8b588091-7a6f-4eda-ac75-c28d5dfbcf44.jpg)

**Comment by Jaewan-Yun** [comment]
Did you install it from Mozilla webstore? Could you post the extension error log if you can access that within the app?

**Comment by blader-render** [comment]
Yup, I install from mozila webstrore. ![az_recorder_20221228_121801.jpg](https://user-images.githubusercontent.com/120096290/209762007-9da7994e-b586-4f08-b752-943a216f0b4e.jpg)

**Comment by king-iskan** [comment]
This issue already close? But still not working. Why? Please, can you explain how to use extension in firefox nightly (android).
