### ISSUE TITLE
Residential IP detected as Proxy/VPN

### ISSUE THREAD

**Issue by xscd** [nopecha-ai/nopecha-extension#4]
Hi, I have been using the extension for a few weeks now. It used to work until a few days (not sure when the change was made but noticed today) my IP is from a Turkish ISP and not a Proxy/VPN. Can this strict IP limitation removed? 

AFAIK Turkiye and lots of other countries use Carrier-grade NAT could this be the reason? 

![image](https://user-images.githubusercontent.com/46658470/210059562-077f07c5-f3e3-455e-9c06-160afadf5613.png)

**Comment by Jaewan-Yun** [comment]
We broke our bot detection algorithm yesterday. It should be fixed now. Let us know what IP you're on (via Discord) if you're still seeing that message.

**Comment by xscd** [comment]
I send you a DM on Discord. The issue seems to be not solved. I shared you my IP on Discord.
