### ISSUE TITLE
Turn off the auto-open for the chrome extension while using the selenium

### ISSUE THREAD

**Issue by nathantian** [nopecha-ai/nopecha-extension#5]
Hi - Thanks a lot for building such a great extension. 

I was trying to load the chrome extension on the selenium chrome driver, but one thing I would like to achieve is, not to auto-open  the hcaptcha, but let the selenium to control when we want to click on the check box. Is it possible to program the config of the extension using selenium? Thank you!

**Comment by Jaewan-Yun** [comment]
Yes. Configure the extension then click export settings. This will generate a URL that you can programmatically visit in Selenium during startup to import the extension configuration.

**Comment by nathantian** [comment]
awesome ! thank you for the quick response !
